title: Lerntagebuch Blog Test
author: Helen
email: helen@techstarter.de
description: > # this means to ignore newlines
  Vorlage für ein Lerntagebuch

# social links
twitter_username: helen # DO NOT include the @ character, or else the build will fail!
github_username:  helsoc7 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
